// @ts-check
// exporter.js — Diagnostic Report Exporter (JSON, Markdown, Print/PDF)

import { escapeHtml } from '../utils/helpers.js';

/**
 * Trigger browser file download.
 * @param {string} content
 * @param {string} filename
 * @param {string} mimeType
 */
export function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * Export scan report as structured JSON.
 * @param {object} reportData
 */
export function exportAsJson(reportData) {
  const domain   = reportData.domain || 'scan';
  const filename = `sitescope-report-${domain.replace(/[^a-z0-9.-]/gi, '_')}.json`;
  const jsonStr  = JSON.stringify(reportData, null, 2);
  downloadFile(jsonStr, filename, 'application/json');
}

/**
 * Export scan report as Markdown documentation.
 * @param {object} reportData
 */
export function exportAsMarkdown(reportData) {
  const domain    = reportData.domain || 'Target Site';
  const timestamp = new Date(reportData.timestamp || Date.now()).toISOString();
  const sc        = reportData.scorecard || {};
  const sec       = reportData.security || {};

  let md = `# 🛡️ SiteScope Diagnostic Report — ${domain}\n\n`;
  md += `**Generated:** ${timestamp}  \n`;
  md += `**Target URL:** ${reportData.url || domain}  \n`;
  md += `**Security Grade:** **${sc.grade || 'N/A'}** (${sc.score || 0}/100)  \n`;
  md += `**Category:** ${reportData.category?.label || 'General'} ${reportData.category?.emoji || '🌐'}  \n\n`;

  md += `---\n\n## 📊 Security Scorecard Summary\n\n`;
  if (sc.strengths && sc.strengths.length) {
    md += `### ✅ Strengths\n`;
    sc.strengths.forEach((st) => (md += `- ${st}\n`));
    md += `\n`;
  }

  if (sc.remediations && sc.remediations.length) {
    md += `### ⚠️ Remediation Checklist (${sc.remediations.length} action items)\n\n`;
    md += `| Severity | Issue | Remediation |\n`;
    md += `|---|---|---|\n`;
    sc.remediations.forEach((r) => {
      md += `| **${r.severity.toUpperCase()}** | ${r.title} | ${r.description} |\n`;
    });
    md += `\n`;
  }

  md += `## 🛡️ Threat Scanner Report\n\n`;
  md += `**Threat Level:** ${sec.level || 'Unknown'}  \n`;
  md += `**Database Status:** ${sec.dbStatus || 'Clean'}  \n\n`;
  if (sec.findings && sec.findings.length) {
    md += `### Findings:\n`;
    sec.findings.forEach((f) => (md += `- [${f.type.toUpperCase()}] ${f.text}\n`));
    md += `\n`;
  }

  if (reportData.httpHeaders) {
    md += `## 🌐 HTTP Security Headers\n\n\`\`\`json\n`;
    md += JSON.stringify(reportData.httpHeaders, null, 2);
    md += `\n\`\`\`\n\n`;
  }

  md += `---\n*Report generated by SiteScope v4 (https://sitescope-omega.vercel.app)*\n`;

  const filename = `sitescope-report-${domain.replace(/[^a-z0-9.-]/gi, '_')}.md`;
  downloadFile(md, filename, 'text/markdown');
}

/**
 * Trigger print dialog formatted as PDF/Paper report.
 */
export function triggerPrintReport() {
  window.print();
}
