// @ts-check
// exporter.js — Diagnostic Report Exporter (JSON, Markdown, Print/PDF)


/**
 * Trigger browser file download.
 * @param {string} content
 * @param {string} filename
 * @param {string} mimeType
 */
export function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * @typedef {{
 *   url?: string,
 *   domain?: string,
 *   timestamp?: string|number,
 *   category?: { label?: string, emoji?: string },
 *   security?: import('../modules/security.js').ScanResult,
 *   scorecard?: import('../modules/scorecard.js').ScorecardResult,
 *   httpHeaders?: Record<string, string>,
 *   pagespeed?: import('./pagespeed.js').PageSpeedResult,
 *   subdomains?: import('./subdomains.js').SubdomainResult
 * }} ReportData
 */

/**
 * Export scan report as structured JSON.
 * @param {ReportData} reportData
 */
export function exportAsJson(reportData) {
  const domain   = reportData.domain || 'scan';
  const filename = `sitescope-report-${domain.replace(/[^a-z0-9.-]/gi, '_')}.json`;
  const jsonStr  = JSON.stringify(reportData, null, 2);
  downloadFile(jsonStr, filename, 'application/json');
}

/**
 * Export scan report as Markdown documentation.
 * @param {ReportData} reportData
 */
export function exportAsMarkdown(reportData) {
  const domain    = reportData.domain || 'Target Site';
  const timestamp = new Date(reportData.timestamp || Date.now()).toISOString();
  const sc  = reportData.scorecard;
  const sec = reportData.security;

  let md = `# 🛡️ SiteScope Diagnostic Report — ${domain}\n\n`;
  md += `**Generated:** ${timestamp}  \n`;
  md += `**Target URL:** ${reportData.url || domain}  \n`;
  md += `**Security Grade:** **${sc?.grade || 'N/A'}** (${sc?.score ?? 0}/100)  \n`;
  md += `**Category:** ${reportData.category?.label || 'General'} ${reportData.category?.emoji || '🌐'}  \n\n`;

  md += `---\n\n## 📊 Security Scorecard Summary\n\n`;
  if (sc?.strengths && sc.strengths.length) {
    md += `### ✅ Strengths\n`;
    sc.strengths.forEach((st) => (md += `- ${st}\n`));
    md += `\n`;
  }

  if (sc?.remediations && sc.remediations.length) {
    md += `### ⚠️ Remediation Checklist (${sc.remediations.length} action items)\n\n`;
    md += `| Severity | Issue | Remediation |\n`;
    md += `|---|---|---|\n`;
    sc.remediations.forEach((r) => {
      md += `| **${r.severity.toUpperCase()}** | ${r.title} | ${r.description} |\n`;
    });
    md += `\n`;
  }

  md += `## 🛡️ Threat Scanner Report\n\n`;
  md += `**Threat Level:** ${sec?.level || 'Unknown'}  \n`;
  md += `**Database Status:** ${sec?.dbStatus || 'Clean'}  \n\n`;
  if (sec?.findings && sec.findings.length) {
    md += `### Findings:\n`;
    sec.findings.forEach((f) => (md += `- [${f.type.toUpperCase()}] ${f.text}\n`));
    md += `\n`;
  }

  if (reportData.pagespeed && !reportData.pagespeed.error) {
    const ps = reportData.pagespeed;
    md += `## ⚡ Google PageSpeed Insights & Core Web Vitals\n\n`;
    md += `| Category | Score |\n|---|---|\n`;
    md += `| **Performance** | ${ps.scores.performance ?? 'N/A'}/100 |\n`;
    md += `| **Accessibility** | ${ps.scores.accessibility ?? 'N/A'}/100 |\n`;
    md += `| **Best Practices** | ${ps.scores.bestPractices ?? 'N/A'}/100 |\n`;
    md += `| **SEO** | ${ps.scores.seo ?? 'N/A'}/100 |\n\n`;

    if (ps.metrics.length) {
      md += `### Core Web Vitals\n\n`;
      md += `| Metric | Value | Rating |\n|---|---|---|\n`;
      ps.metrics.forEach((m) => {
        md += `| **${m.title} (${m.name})** | ${m.value} | ${m.rating.toUpperCase()} |\n`;
      });
      md += `\n`;
    }
  }

  if (reportData.subdomains && !reportData.subdomains.error && reportData.subdomains.totalCount > 0) {
    const sub = reportData.subdomains;
    md += `## 🕸️ Discovered Subdomains (${sub.totalCount})\n\n`;
    sub.subdomains.forEach((s) => (md += `- \`${s}\`\n`));
    md += `\n`;
  }

  if (reportData.httpHeaders) {
    md += `## 🌐 HTTP Security Headers\n\n\`\`\`json\n`;
    md += JSON.stringify(reportData.httpHeaders, null, 2);
    md += `\n\`\`\`\n\n`;
  }

  md += `---\n*Report generated by SiteScope v4 (https://sitescope-omega.vercel.app)*\n`;

  const filename = `sitescope-report-${domain.replace(/[^a-z0-9.-]/gi, '_')}.md`;
  downloadFile(md, filename, 'text/markdown');
}

/**
 * Trigger print dialog formatted as PDF/Paper report.
 */
export function triggerPrintReport() {
  window.print();
}
